foundersandcoders/nazareth-events

- .eslintrc.js
- .gitignore
- package.json
- server.js
- start.js
> Set up server

- .gitignore
- public/css/main.css
- public/js/main.js
- routes/home.js
- routes/index.js
- server.js
- views/home.hbs
- views/layouts/main.hbs
- views/partials/header.hbs
> List events

- package.json
> removed express from devDependencies, installed in dependencies

- README.md
> write a readme file

- public/js/render.js
- server.js
> Date format

- public/css/main.css
- routes/home.js
- views/event_details.hbs
- views/partials/header.hbs
> Calendar button event detail

- public/js/get_events.js
- public/js/main.js
- public/js/render.js
> Order events from current day

- package-lock.json
- package.json
- server.js
Reverts foundersandcoders/nazareth-events#54
Woops - need to run `npm i` first I think to update `package-lock.json`
> Revert "Compression"

- package-lock.json
- package.json
- server.js
> Compression

- public/js/render.js
> Show events places on homepage

- .gitignore
- public/js/render.js
- views/event_details.hbs
> some changes on home page 

- routes/add_event.js
> fixed bug 

- public/js/render.js
> Render a place in home

- public/css/main.css
- public/js/main.js
- public/js/render.js
- views/partials/header.hbs
> Filter arabic english

- routes/add_event.js
- routes/middleware/post_place.js
- views/add_event.hbs
rel #67 
Those changes came from [the comment](https://github.com/foundersandcoders/nazareth-events/issues/67#issuecomment-334117763) the @mattlub wrote.
but if you think theres more to be changed in this form **write a comment**
> Place form inputs change

- public/css/main.css
- public/js/render.js
- views/home.hbs
- views/partials/header.hbs
> Minor style changes

- public/css/main.css
- routes/home.js
- views/add_event.hbs
- views/event_details.hbs
- views/partials/header.hbs
> Event details design

- public/css/main.css
- public/js/add_place.js
- routes/render_add_form.js
- views/add_event.hbs
- views/event_details.hbs
- views/layouts/main.hbs
> Style form

- public/css/main.css
- public/js/render.js
- routes/event_details.js
- routes/index.js
- views/event_details.hbs
- views/partials/header.hbs
> Final touches (maybe)

- public/js/get_events.js
- routes/add_event.js
- routes/event_details.js
- routes/middleware/get_places.js
- routes/middleware/post_place.js
> Adds api/v1 to the api url

- public/css/main.css
- public/js/validate_form.js
- routes/add_event.js
- tests/tests.js
- views/add_event.hbs
- views/layouts/main.hbs
> Client side Validation

- public/css/main.css
- views/error.hbs
- views/home.hbs
- views/layouts/main.hbs
#116 
This is 1 part of the #110 issue
> Error view

- public/css/main.css
- views/add_event.hbs
> Place details fields

- .eslintrc.js
- public/js/filter_listeners.js
- public/js/helpers/get_startTime.js
- public/js/main.js
- public/js/validate_form.js
- views/add_event.hbs
- webpack.dev.config.js
- webpack.prod.config.js
> Fix frontend scripts logging errors

- public/js/filter_listeners.js
- routes/home.js
- routes/middleware/post_place.js
- tests/tests.js
- views/partials/header.hbs
> Filter categories functionality

- public/js/calendar.js
- public/js/filter_listeners.js
- public/js/helpers/date.js
- public/js/helpers/get_startTime.js
- public/js/main.js
- public/js/validate_form.js
> Refactor frontend to ES6

- public/css/main.css
- public/js/filter_listeners.js
- views/event_details.hbs
- views/home.hbs
- views/partials/header.hbs
> fix some styling issues 

- package-lock.json
- package.json
- server.js
- views/helpers/checkCategory.js
- views/helpers/findNamelang.js
- views/helpers/findPlaceLang.js
- views/helpers/prettyDate.js
- views/helpers/prettyTime.js
- views/helpers/removeProtocol.js
- webpack.dev.config.js
- webpack.prod.config.js
close #149 
setup handlebars-loader in webpack and moves helpers into a directory.
*this was also checked by importing the hbs file in the frontend*
> Bundle hbs files

- package-lock.json
- package.json
- public/js/filter_listeners.js
- public/js/helpers/get_startTime.js
- public/js/main.js
- public/js/template.js
- routes/event_details.js
- routes/home.js
- tests/tests.js
- views/layouts/main.hbs
- webpack.dev.config.js
- webpack.prod.config.js
> Connect hbs template frontend

- public/js/filter_listeners.js
- public/js/template.js
- routes/home.js
- server.js
- views/helpers/getLength.js
- views/home.hbs
#155 
this PR does not contain the styling for this component.
@finnhodgkin do you think the styling should be in the PR or a different one ?
> Events results bar

- public/js/filter_listeners.js
- public/js/helpers/get_startTime.js
- public/js/template.js
> adds the search bar functionality

- public/css/main.css
- public/js/calendar.js
- public/js/main.js
> Enhance calendar UX/UI

- views/layouts/main.hbs
#164
Google analytics was setup on the OTP gmail account.
> Adds google analytics 

- public/css/main.css
- views/layouts/main.hbs
> Desktop compatibility 

- public/js/filter_listeners.js
- public/js/helpers/get_startTime.js
- public/js/main.js
- public/js/template.js
> Serach input bug
